// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flag"
	"github.com/BurntSushi/toml"
	"github.com/didip/tollbooth/v7"
	"github.com/didip/tollbooth/v7/limiter"
	"github.com/gin-gonic/gin"
	"log"
	"net/http"
	"os"
	"time"
)

// Injectors from container.go:

func initializeApplication() *Application {
	logger := setupLogging()
	config := initializeConfig(logger)
	limiter := setupRatelimiting()
	mainUninitializedApplication := &uninitializedApplication{
		Logger:      logger,
		config:      config,
		RateLimiter: limiter,
	}
	application := addRouter(mainUninitializedApplication)
	return application
}

// container.go:

func setupLogging() *Logger {
	flags := log.Ldate | log.Ltime | log.Lshortfile | log.Lmsgprefix

	return &Logger{
		logInfo:    log.New(os.Stdout, "INFO: ", flags),
		logError:   log.New(os.Stdout, "ERROR: ", flags),
		logWarning: log.New(os.Stdout, "WARN: ", flags),
	}
}

func initializeConfig(l *Logger) (c Config) {
	var configLocation string
	flag.StringVar(&configLocation, "c", "config.toml", "Location of config file")
	flag.Parse()

	rawConfig, err := os.ReadFile(configLocation)
	if err != nil {
		l.logError.Fatal(err)
	}

	if _, err = toml.Decode(string(rawConfig), &c); err != nil {
		l.logError.Fatal(err)
	}

	return
}

func setupRatelimiting() *limiter.Limiter {
	rateLimiter := tollbooth.NewLimiter(2, &limiter.ExpirableOptions{DefaultExpirationTTL: time.Hour})
	rateLimiter.SetIPLookups([]string{"X-Forwarded-For", "RemoteAddr", "X-Real-IP"})

	return rateLimiter
}

func addRouter(uninitializedApp *uninitializedApplication) (app *Application) {
	app = (*Application)(uninitializedApp)
	app.logInfo.Println("Setting up router")
	gin.SetMode(gin.ReleaseMode)
	app.Router = gin.Default()

	api := app.Router.Group("/api")
	api.GET("/limited-account-value", app.limitedAccountValueAPI)
	api.GET("/can-view-inventory", app.canViewInventoryAPI)
	api.Use(app.ratelimitMiddleware())

	app.Router.GET("/", func(c *gin.Context) {
		c.Redirect(http.StatusTemporaryRedirect, "https://github.com/ayes-web/roblox-account-value-api")
	})

	return
}

type uninitializedApplication Application
